org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.2
minecraft_version_range=[1.20.2, 1.21)
neo_version=20.2.93
neo_version_range=[20.2,)
loader_version_range=[1,)

mod_id=emeraldcraft
mod_name=Emerald Craft Mod
mod_license=MIT
mod_version=9.2.0
mod_authors=Liu Dongyu
mod_issue_tracker=https://github.com/Viola-Siemens/EmeraldCraftMod/issues
mod_description=More crafts, biomes, piglin girls, and cute villagers!\nI love villagers in minecraft. I hope so do you. And I also love piglins -- just because they look like girls with head covers!\nWith this mod, you can trade many other things with villagers, and with piglin-cutey, a new mob in the nether.\nYou can also do the emerald craft, the gold craft, and even craft some "trash" into building material to decorate your house with this mod!