modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Viola-Siemens/EmeraldCraftMod/issues"

[[mods]]
modId="emeraldcraft"
version="${file.jarVersion}"
displayName="Emerald Craft Mod"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
More crafts, biomes, piglin girls, and cute villagers!

I love villagers in minecraft. I hope so do you. And I also love piglins -- just because they look like girls with head covers!

With this mod, you can trade many other things with villagers, and with piglin-cutey, a new mob in the nether.

You can also do the emerald craft, the gold craft, and even craft some "trash" into building material to decorate your house with this mod!
'''

[[dependencies.emeraldcraft]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.emeraldcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.emeraldcraft]]
    modId="terrablender"
    mandatory=false
    versionRange="[3.0.0.164,)"
    ordering="NONE"
    side="BOTH"