modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId="emeraldcraft"
version="${file.jarVersion}"
displayName="Emerald Craft Mod"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
More crafts, biomes, piglin varieties, and cute villagers!

Liu Dongyu's first mod. This is a comprehensive mod for blocks, biomes, entities, foods, structures, and especially trades and recipes.

I love villagers in minecraft. I hope so do you. And I also love piglins -- just because they look like girls with head covers!

This mod adds some food, crops and more useful items craft by something common, too.

With this mod, you can trade many other things with villagers, and new mobs in the nether. Additionally, what about cure zombified piglins and let them work only for you?

You can also do the emerald craft, the gold craft, and even craft some "trash" into building material to decorate your house with this mod!
'''
[[dependencies.emeraldcraft]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.emeraldcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.emeraldcraft]]
	modId="terrablender"
	mandatory=true
	versionRange="[2.0.0.120,)"
	ordering="NONE"
	side="BOTH"
