name: New Feature Request
description: What features would you like to add in Emerald Craft?
title: "[Enhancement]: "
labels: [ "Enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your supporting!
  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of the feature would you describe?
      options:
      - label: Loot Table for Blocks or Continuous Miner
      - label: Texture for Blocks or Entities
      - label: Biomes
      - label: Recipes and GUI
      - label: Professions and Trades of Villagers
      - label: Features
      - label: Structures
      - label: Useful Blocks and Items
      - label: Entities
      - label: Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the feature
      description: What can Emerald Craft mod do for you?
      placeholder: Feel free to describe what you thought :)
    validations:
      required: true